import { useState } from "react";
import { Bell, KeyRound, Save } from "lucide-react";
import { authService } from "../../services/authService";
import { useToast } from "../../context/useToast";

export function SettingsPage() {
  const toast = useToast();
  const [form, setForm] = useState({ current_password: "", new_password: "", confirm_password: "" });
  const [notifications, setNotifications] = useState(() => localStorage.getItem("knowledge-desk-notifications") !== "off");
  const [busy, setBusy] = useState(false);
  const change = (key) => (event) => setForm((current) => ({ ...current, [key]: event.target.value }));
  const submitPassword = async (event) => { event.preventDefault(); if (form.new_password.length < 8) { toast.push("Use at least 8 characters for the new password.", "error"); return; } if (form.new_password !== form.confirm_password) { toast.push("New passwords do not match.", "error"); return; } setBusy(true); try { await authService.changePassword({ current_password: form.current_password, new_password: form.new_password, confirm_new_password: form.confirm_password }); setForm({ current_password: "", new_password: "", confirm_password: "" }); toast.push("Password changed."); } catch (caught) { toast.push(caught?.message || "Password could not be changed.", "error"); } finally { setBusy(false); } };
  const saveNotifications = () => { localStorage.setItem("knowledge-desk-notifications", notifications ? "on" : "off"); toast.push("Settings saved."); };
  return <div className="h-full overflow-y-auto bg-canvas-100"><div className="mx-auto max-w-4xl px-5 py-10 sm:px-8 lg:py-14"><header className="border-b border-carbon-950 pb-8"><p className="font-mono text-[9px] uppercase tracking-[0.22em] text-vermilion-600">Account / preferences</p><h1 className="mt-3 font-display text-[clamp(3rem,7vw,6rem)] leading-[0.84] tracking-[-0.055em]">Make it <span className="italic text-vermilion-500">yours.</span></h1></header><div className="mt-8 grid gap-6 lg:grid-cols-2"><section className="border border-carbon-950 bg-canvas-50 p-5 sm:p-7"><div className="flex items-center gap-3 border-b border-canvas-300 pb-5"><KeyRound size={18} className="text-vermilion-500" aria-hidden="true" /><div><h2 className="font-display text-2xl">Password</h2><p className="text-xs text-carbon-500">Rotate your workspace credential.</p></div></div><form onSubmit={submitPassword} className="mt-6 space-y-4"><Field id="current-password" label="Current password" value={form.current_password} onChange={change("current_password")} /><Field id="new-password" label="New password" value={form.new_password} onChange={change("new_password")} /><Field id="confirm-password" label="Confirm new password" value={form.confirm_password} onChange={change("confirm_password")} /><button type="submit" disabled={busy} className="min-h-11 bg-carbon-950 px-4 text-xs font-semibold text-canvas-50 hover:bg-vermilion-500 disabled:opacity-50 focus-visible:outline-none">{busy ? "Updating..." : "Update password"}</button></form></section><section className="border border-carbon-950 bg-canvas-50 p-5 sm:p-7"><div className="flex items-center gap-3 border-b border-canvas-300 pb-5"><Bell size={18} className="text-moss-500" aria-hidden="true" /><div><h2 className="font-display text-2xl">Notifications</h2><p className="text-xs text-carbon-500">Control workspace alerts on this device.</p></div></div><label className="mt-7 flex cursor-pointer items-start gap-3"><input type="checkbox" checked={notifications} onChange={(event) => setNotifications(event.target.checked)} className="mt-1 h-4 w-4 accent-vermilion-500 focus-visible:outline-none" /><span><span className="block text-sm font-semibold">Show activity notifications</span><span className="mt-1 block text-xs leading-5 text-carbon-500">Keep success and error feedback visible while you work.</span></span></label><button type="button" onClick={saveNotifications} className="mt-7 flex min-h-11 items-center gap-2 border border-carbon-950 px-4 text-xs font-semibold hover:bg-carbon-950 hover:text-canvas-50 focus-visible:outline-none"><Save size={14} aria-hidden="true" /> Save preference</button></section></div></div></div>;
}

function Field({ id, label, value, onChange }) { return <div><label htmlFor={id} className="mb-2 block font-mono text-[9px] uppercase tracking-[0.18em] text-carbon-500">{label}</label><input id={id} type="password" value={value} onChange={onChange} required className="min-h-11 w-full border border-carbon-950 bg-canvas-50 px-3 text-sm focus:outline-none focus:ring-2 focus:ring-vermilion-500" autoComplete="new-password" /></div>; }
