import { useEffect, useState } from "react";
import { ClipboardList, RefreshCw } from "lucide-react";
import { adminService } from "../../services/adminService";

export function AdminAuditLogPage() {
  const [entries, setEntries] = useState([]); const [loading, setLoading] = useState(true); const [error, setError] = useState("");
  const load = async () => { setLoading(true); setError(""); try { setEntries(await adminService.listAuditLog()); } catch (caught) { setError(caught?.message || "Audit log could not be loaded."); } finally { setLoading(false); } };
  useEffect(() => { load(); }, []);
  return <div className="h-full overflow-y-auto"><div className="mx-auto max-w-6xl px-5 py-10 sm:px-8 lg:py-14"><header className="flex flex-col gap-6 border-b border-carbon-950 pb-8 sm:flex-row sm:items-end sm:justify-between"><div><p className="font-mono text-[9px] uppercase tracking-[0.22em] text-vermilion-600">Control room / accountability</p><h1 className="mt-3 font-display text-[clamp(3rem,7vw,6.5rem)] leading-[0.82] tracking-[-0.055em]">Audit <span className="italic text-vermilion-500">log.</span></h1><p className="mt-5 max-w-xl text-sm leading-7 text-carbon-500">A durable record of identity, access, and recovery decisions.</p></div><button type="button" onClick={load} disabled={loading} className="flex min-h-10 items-center gap-2 self-start border border-carbon-950 px-3 text-xs font-semibold hover:bg-carbon-950 hover:text-canvas-50 disabled:opacity-50 focus-visible:outline-none"><RefreshCw size={14} aria-hidden="true" /> Refresh</button></header>{error && <p role="alert" className="mt-5 border-l-4 border-vermilion-500 bg-[#F8E9E3] px-4 py-3 text-sm text-vermilion-600">{error}</p>}<div className="mt-8 overflow-x-auto border-y border-carbon-950">{loading ? <div aria-label="Loading audit log" className="space-y-px bg-canvas-300">{[1, 2, 3, 4].map((item) => <div key={item} className="h-16 animate-pulse bg-canvas-50" />)}</div> : entries.length ? <table className="w-full min-w-[48rem] text-left"><thead className="border-b border-carbon-950 font-mono text-[9px] uppercase tracking-[0.14em] text-carbon-500"><tr><th className="px-3 py-3 font-normal">When</th><th className="px-3 py-3 font-normal">Actor</th><th className="px-3 py-3 font-normal">Action</th><th className="px-3 py-3 font-normal">Target</th><th className="px-3 py-3 font-normal">Detail</th></tr></thead><tbody>{entries.map((entry, index) => <tr key={entry.id || index} className="border-b border-canvas-300 last:border-0"><td className="whitespace-nowrap px-3 py-4 font-mono text-[9px] uppercase tracking-[0.08em] text-carbon-500">{formatDate(entry.created_at || entry.timestamp)}</td><td className="px-3 py-4 text-xs">{entry.actor_email || entry.user_email || entry.actor || "System"}</td><td className="px-3 py-4"><span className="border border-canvas-300 px-2 py-1 font-mono text-[9px] uppercase tracking-[0.1em]">{entry.action || entry.event_type || "Event"}</span></td><td className="px-3 py-4 text-xs text-carbon-700">{entry.target_type ? `${entry.target_type} / ` : ""}{entry.target_id || "Not specified"}</td><td className="max-w-xs px-3 py-4 text-xs leading-5 text-carbon-500">{safeDetail(entry.detail || entry.metadata || entry.reason)}</td></tr>)}</tbody></table> : <div className="bg-canvas-50 px-6 py-12 text-center"><ClipboardList size={28} className="mx-auto text-moss-500" aria-hidden="true" /><p className="mt-4 font-display text-2xl">No audit entries yet</p><p className="mt-2 text-sm text-carbon-500">Recorded admin actions will appear here.</p></div>}</div></div></div>;
}

function formatDate(value) { if (!value) return "No timestamp"; const date = new Date(value); return Number.isNaN(date.getTime()) ? "No timestamp" : date.toLocaleString(); }
function safeDetail(value) { if (value === null || value === undefined) return "No detail provided."; if (typeof value === "string" || typeof value === "number") return String(value); try { return JSON.stringify(value); } catch { return "Detail unavailable."; } }

