import { useEffect, useState } from "react";
import { Activity, FileText, MessageSquare, Users, RefreshCw } from "lucide-react";
import { adminService } from "../../services/adminService";

const metricDefinitions = [["total_users", "People", Users], ["total_conversations", "Conversations", MessageSquare], ["total_documents", "Documents", FileText], ["pending_restore_requests", "Restore requests", Activity]];

export function AdminOverviewPage() {
  const [overview, setOverview] = useState(null);
  const [error, setError] = useState("");
  const [loading, setLoading] = useState(true);
  const load = async () => { setLoading(true); setError(""); try { setOverview(await adminService.getOverview()); } catch (caught) { setError(caught?.message || "Admin overview could not be loaded."); } finally { setLoading(false); } };
  useEffect(() => { load(); }, []);
  return <div className="h-full overflow-y-auto"><div className="mx-auto max-w-7xl px-5 py-10 sm:px-8 lg:py-14"><header className="flex flex-col gap-6 border-b border-carbon-950 pb-8 sm:flex-row sm:items-end sm:justify-between"><div><p className="font-mono text-[9px] uppercase tracking-[0.22em] text-vermilion-600">Control room / overview</p><h1 className="mt-3 font-display text-[clamp(3rem,7vw,6.5rem)] leading-[0.82] tracking-[-0.055em]">System <span className="italic text-vermilion-500">pulse.</span></h1><p className="mt-5 max-w-xl text-sm leading-7 text-carbon-500">A concise view of access, conversations, evidence, and recovery work.</p></div><button type="button" onClick={load} disabled={loading} className="flex min-h-10 items-center justify-center gap-2 self-start border border-carbon-950 px-3 text-xs font-semibold hover:bg-carbon-950 hover:text-canvas-50 disabled:opacity-50 focus-visible:outline-none"><RefreshCw size={14} aria-hidden="true" /> Refresh</button></header>{error && <p role="alert" className="mt-6 border-l-4 border-vermilion-500 bg-[#F8E9E3] px-4 py-3 text-sm text-vermilion-600">{error}</p>}<div className="mt-8 grid gap-px bg-canvas-300 sm:grid-cols-2 xl:grid-cols-4">{metricDefinitions.map(([key, label, Icon]) => <div key={key} className="bg-canvas-50 p-5 sm:p-6"><Icon size={18} className="text-vermilion-500" aria-hidden="true" /><p className="mt-7 font-display text-5xl italic text-carbon-950">{loading ? "--" : formatNumber(overview?.metrics?.[key] ?? overview?.[key] ?? overview?.counts?.[key])}</p><p className="mt-2 font-mono text-[9px] uppercase tracking-[0.16em] text-carbon-500">{label}</p></div>)}</div><div className="mt-8 grid gap-8 lg:grid-cols-[minmax(0,1fr)_20rem]"><section className="border-t border-carbon-950 pt-4"><p className="font-mono text-[9px] uppercase tracking-[0.18em] text-carbon-500">Operational notes</p><div className="mt-4 space-y-px">{(overview?.highlights || overview?.activity || []).slice(0, 6).map((item, index) => <div key={item.id || index} className="grid gap-2 border-b border-canvas-300 py-4 sm:grid-cols-[8rem_minmax(0,1fr)]"><p className="font-mono text-[9px] uppercase tracking-[0.12em] text-carbon-500">{item.label || item.type || "Signal"}</p><p className="text-sm text-carbon-700">{item.message || item.description || item.value || "No detail provided."}</p></div>)}{!loading && !(overview?.highlights || overview?.activity || []).length && <p className="py-8 text-sm text-carbon-500">No recent operational notes.</p>}</div></section><aside className="border-l-2 border-moss-500 bg-[#E3ECE4] p-5"><p className="font-mono text-[9px] uppercase tracking-[0.18em] text-moss-500">Access boundary</p><p className="mt-3 font-display text-2xl text-carbon-950">Review before action.</p><p className="mt-3 text-xs leading-5 text-carbon-700">Admin actions are recorded and restore decisions remain explicit.</p></aside></div></div></div>;
}

function formatNumber(value) { const number = Number(value); return Number.isFinite(number) ? number.toLocaleString() : "--"; }
