import { useEffect, useMemo, useState } from "react";
import { Eye, Search } from "lucide-react";
import { AdminPipelineDrawer } from "../../components/AdminPipelineDrawer";
import { adminService } from "../../services/adminService";

export function AdminConversationsPage() {
  const [conversations, setConversations] = useState([]); const [selected, setSelected] = useState(null); const [query, setQuery] = useState(""); const [loading, setLoading] = useState(true); const [error, setError] = useState("");
  const load = async () => { setLoading(true); setError(""); try { setConversations(await adminService.listConversations()); } catch (caught) { setError(caught?.message || "Conversations could not be loaded."); } finally { setLoading(false); } };
  useEffect(() => { load(); }, []);
  const filtered = useMemo(() => conversations.filter((item) => `${item.title || ""} ${item.user_email || item.owner_email || ""}`.toLowerCase().includes(query.toLowerCase())), [conversations, query]);
  const inspect = async (conversation) => { try { setSelected(conversation.messages ? conversation : await adminService.getConversation(conversation)); } catch (caught) { setError(caught?.message || "Conversation details could not be loaded."); } };
  return <Frame><div className="mb-5 flex flex-col gap-3 sm:flex-row sm:items-center sm:justify-between"><label className="relative block w-full sm:max-w-md"><span className="sr-only">Search conversations</span><Search size={15} className="pointer-events-none absolute left-3 top-1/2 -translate-y-1/2 text-carbon-500" aria-hidden="true" /><input type="search" value={query} onChange={(event) => setQuery(event.target.value)} placeholder="Search title or owner" className="min-h-11 w-full border border-carbon-950 bg-canvas-50 px-3 pl-9 text-sm focus:outline-none focus:ring-2 focus:ring-vermilion-500" /></label><p className="font-mono text-[9px] uppercase tracking-[0.14em] text-carbon-500">{filtered.length} record{filtered.length === 1 ? "" : "s"}</p></div>{error && <p role="alert" className="mb-5 border-l-4 border-vermilion-500 bg-[#F8E9E3] px-4 py-3 text-sm text-vermilion-600">{error}</p>}<div className="overflow-x-auto border-y border-carbon-950">{loading ? <LoadingRows /> : filtered.length ? <table className="w-full min-w-[44rem] text-left"><thead className="border-b border-carbon-950 font-mono text-[9px] uppercase tracking-[0.14em] text-carbon-500"><tr><th className="px-3 py-3 font-normal">Conversation</th><th className="px-3 py-3 font-normal">Owner</th><th className="px-3 py-3 font-normal">State</th><th className="px-3 py-3 text-right font-normal">Inspect</th></tr></thead><tbody>{filtered.map((conversation, index) => <tr key={conversation.id || index} className="border-b border-canvas-300 last:border-0"><td className="px-3 py-4"><p className="font-semibold">{conversation.title || "Untitled conversation"}</p><p className="mt-1 font-mono text-[9px] uppercase tracking-[0.1em] text-carbon-500">{formatDate(conversation.created_at || conversation.createdAt)}</p></td><td className="px-3 py-4 text-xs text-carbon-500">{conversation.user_email || conversation.owner_email || "Unassigned"}</td><td className="px-3 py-4"><span className={`font-mono text-[9px] uppercase tracking-[0.1em] ${conversation.is_deleted ? "text-vermilion-600" : "text-moss-500"}`}>{conversation.is_deleted ? "deleted" : "active"}</span></td><td className="px-3 py-4 text-right"><button type="button" onClick={() => inspect(conversation)} className="inline-flex min-h-9 items-center gap-2 border border-carbon-950 px-3 text-xs hover:bg-carbon-950 hover:text-canvas-50 focus-visible:outline-none"><Eye size={14} aria-hidden="true" /> Open trace</button></td></tr>)}</tbody></table> : <p className="px-3 py-12 text-sm text-carbon-500">No conversations match this search.</p>}</div><AdminPipelineDrawer conversation={selected} open={Boolean(selected)} onClose={() => setSelected(null)} /></Frame>;
}

function Frame({ children }) { return <div className="h-full overflow-y-auto"><div className="mx-auto max-w-7xl px-5 py-10 sm:px-8 lg:py-14"><header className="border-b border-carbon-950 pb-8"><p className="font-mono text-[9px] uppercase tracking-[0.22em] text-vermilion-600">Control room / conversation archive</p><h1 className="mt-3 font-display text-[clamp(3rem,7vw,6.5rem)] leading-[0.82] tracking-[-0.055em]">Conversation <span className="italic text-vermilion-500">ledger.</span></h1><p className="mt-5 max-w-xl text-sm leading-7 text-carbon-500">Inspect retained records and open the assistant trace attached to a completed answer.</p></header><section className="mt-8">{children}</section></div></div>; }
function LoadingRows() { return <div aria-label="Loading conversations" className="space-y-px bg-canvas-300">{[1, 2, 3].map((item) => <div key={item} className="h-20 animate-pulse bg-canvas-50" />)}</div>; }
function formatDate(value) { if (!value) return "No date"; const date = new Date(value); return Number.isNaN(date.getTime()) ? "No date" : date.toLocaleDateString(); }
